apps/core/urls.py
from django.urls import path
from apps.core import views
from django.contrib.auth.views import LogoutView


app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('certificate/', views.FormCertificate.as_view(), name='certificate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sing_up/', views.UserCreateView.as_view(), name='sing_up'),
]

apps/event/urls.py
from django.urls import path, include
from apps.event import views

app_name = 'event'

urlpatterns = [
    path('', views.EventListView.as_view(), name='list'),
    path('add/', views.EventCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.EventUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.EventDeleteView.as_view(), name='delete'),
    path('code/<int:pk>/generate/', views.CodeFormView.as_view(), name='code'),
    path('<int:event_id>/action/', include('apps.action.urls')),
    path('<int:event_id>/product/', include('apps.product.urls')),
    path('<int:event_id>/participant/', include('apps.participant.urls')),
]

apps/people/urls.py
from django.urls import path
from apps.people import views

app_name = 'people'

urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('add/', views.UserCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.UserUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete'),
    path('picture/', views.PictureCreateView.as_view(), name='picture'),
    path(
        'detail/<int:pk>/picture-delete/<int:picture_id>/',
        views.PictureDeleteView.as_view(),
        name='picture-delete'),
    path(
        'detail/<int:pk>/picture-detail/<int:picture_id>/',
        views.PictureDetailView.as_view(),
        name='picture-detail'),
    path(
        'picture-save/',
        views.PictureView.as_view(),
        name='picture-save'),
]

checkin_web/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings

urlpatterns = [
    path('', include('apps.core.urls')),
    path('event/', include('apps.event.urls')),
    path('user/', include('apps.people.urls')),
    # path('api/', include('apps.api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('api/', include('apps.api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/people/forms.py
from django import forms
from django.conf import settings
from apps.people.models import User, Picture
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.models import Group
import re
from django.core.exceptions import ValidationError


class UserForm2(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'email', 'first_name', 'last_name', 'phone', 'birth', 'rg',
            'cpf', 'gender', 'scholarity', 'city', 'province', 'street',
            'number', 'complement', 'neighborhood', 'postal_code']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control'}),
            'rg': forms.TextInput(attrs={'class': 'form-control'}),
            'birth': forms.DateInput(
                        format="%d/%m/%Y", attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),

            'scholarity': forms.Select(attrs={'class': 'form-control'}),

            'province': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'neighborhood': forms.TextInput(attrs={'class': 'form-control'}),
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'number': forms.TextInput(attrs={'class': 'form-control'}),
            'complement': forms.Textarea(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'})
        }
        fieldsets = (
            ('Dados Pessoais', {
                'fields': (
                    'first_name', 'last_name',
                    'gender', 'birth', 'rg', 'cpf',)
            }),
            ('Contato', {
                'fields': ('phone', 'email',)
            }),
            ('Localização', {
                'fields': (
                    'province', 'city', 'neighborhood', 'street',
                    'number', 'postal_code', 'complement')
            }),
        )


class UserForm3(forms.ModelForm):

    def clean_email(self):
        data = self.cleaned_data['email']

        try:
            user = User.objects.get(email=data)
        except Exception as e:
            print(e)
            user = None

        if not user:
            return data
        else:
            raise ValidationError("Email já cadastrado!")

    class Meta:
        model = User
        fields = [
            'email', 'first_name', 'last_name', 'phone', 'birth', 'gender']
        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'true'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'true'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'required': 'true'}),
            'phone': forms.TextInput(
                attrs={'class': 'form-control'}),
            'birth': forms.DateInput(
                        format="%d/%m/%Y", attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
        }
        fieldsets = (
            ('Dados Pessoais', {
                'fields': (
                    'first_name', 'last_name',
                    'gender', 'birth')
            }),
            ('Contato', {
                'fields': ('phone', 'email',)
            }),
        )



class UserForm(forms.Form):
    email = forms.EmailField(
        label='Email', max_length=80, required=True,
        widget=forms.EmailInput(
            attrs={
                'required': True,
                'autocomplete': 'off',
                'placeholder': 'Email'}))
    first_name = forms.CharField(
        label='Nome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Nome'}))
    last_name = forms.CharField(
        label='Sobrenome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Sobrenome'}))
    phone = forms.CharField(
        label='Telefone', max_length=80, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Telefone'}))

    brith = forms.DateField(
        label='Nascimento', required=True,
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(
            attrs={'required': True, 'placeholder': 'Nascimento'}))
    rg = forms.CharField(
        label='RG', required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'RG',
                'autocomplete': 'off',
                'required': True}))
    cpf = forms.CharField(
        label='CPF', required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'autocomplete': 'off',
                'placeholder': 'CPF'}))

    gender = forms.ChoiceField(
        label='Sexo', choices=User.GENDER_CHOICE, required=False,
        widget=forms.Select(attrs={'required': True, }))

    scholarity = forms.ChoiceField(
        label='Escolaridade', choices=User.SCHOLARITY_CHOICE, required=False,
        widget=forms.Select(attrs={'required': True, }))

    city = forms.CharField(
        label='Cidade', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Cidade'}))
    province = forms.ChoiceField(
        label='Estado', choices=User.PROVINCES_CHOICE,
        required=True,
        widget=forms.Select(attrs={}))
    street = forms.CharField(
        label='Rua', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Rua'}))
    number = forms.CharField(
        label='Número', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Número'}))
    complement = forms.CharField(
        label='Complemento', required=False,
        widget=forms.TextInput(
            attrs={'required': False, 'placeholder': 'Complemento'}))
    district = forms.CharField(
        label='Bairro', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Bairro'}))
    postal_code = forms.CharField(
        label='CEP', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'CEP'}))

    def clean_phone(self):
        data = self.cleaned_data['phone']
        return re.sub('[^A-Za-z0-9]+', '', data)

    def clean_password_confirm(self):
        data = self.cleaned_data

        if data["password"] != data['password_confirm']:
            raise ValidationError("Senha não confere!")

        return data['password_confirm']

    def clean_cpf(self):
        data = self.cleaned_data['cpf']
        cpf = re.sub('[^A-Za-z0-9]+', '', data)

        try:
            user = User.objects.get(cpf=cpf)
        except Exception as e:
            user = None

        if not user:
            return cpf
        else:
            raise ValidationError("Cpf já cadastrado!")

    def clean_email(self):
        data = self.cleaned_data['email']

        try:
            user = User.objects.get(email=data)
        except Exception as e:
            user = None

        if not user:
            return data
        else:
            raise ValidationError("Email já cadastrado!")

    class Meta:
        fieldsets = (
            ('Dados Pessoais', {
                'fields': (
                    'first_name', 'last_name',
                    'gender', 'brith', 'rg', 'cpf',)
            }),
            ('Localização', {
                'fields': (
                    'province', 'city', 'street', 'number',
                    'complement', 'district', 'postal_code')
            }),
            ('Contato', {
                'fields': ('phone', 'email',)
            }),
            #     ('Dados Acesso', {
            #         'fields': ('password', 'password_confirm')
            #     }),
        )


class PictureForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        label='', queryset=User.objects.all(),
        widget=forms.HiddenInput)

    class Meta:
        model = Picture
        fields = ['photo', 'user']
        widgets = {
            'user': forms.HiddenInput,
            'photo': forms.FileInput(attrs={
                'required': True,
                'class': 'form-control'}),
        }


class PictureSaveForm(forms.Form):
    user = forms.ModelChoiceField(
        label='User', queryset=User.objects.all(),
        widget=forms.HiddenInput)
    image = forms.CharField(
        label='Image', required=False,
        widget=forms.Textarea(attrs={}))

    class Meta:
        model = Picture
        fields = ['photo', 'user']
        widgets = {
            'user': forms.HiddenInput,
            'photo': forms.FileInput(attrs={
                'required': True,
                'class': 'form-control'}),
        }


class FormProfile(forms.Form):
    first_name = forms.CharField(
        label='Nome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'class': 'form-control', 'placeholder': 'Nome'}))
    last_name = forms.CharField(
        label='Sobrenome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Sobrenome'}))
    phone = forms.CharField(
        label='Telefone', max_length=80, required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'class': 'form-control',

apps/core/views.py
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.views.generic import FormView, RedirectView
from django.contrib.auth.decorators import login_required
from apps.core.forms import FormCustomLogin, SignUpForm, FormCertificate
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.contrib import messages
from apps.event.models import Event
from apps.people.models import User
from apps.people.forms import UserForm3

import io
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from cgi import escape
from weasyprint import HTML


def render_to_pdf(template_src, context_dict):
    htmlstring = get_template(template_src).render(context_dict)
    html = HTML(string=htmlstring)
    main_doc = html.render()
    pdf = main_doc.write_pdf()
    return HttpResponse(pdf, content_type='application/pdf')


class CoreMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CoreMixin, self)\
            .dispatch(request, *args, **kwargs)


class IndexView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update(dict(events=Event.objects.all()))
        return context


class HomeView(TemplateView):
    template_name = "core/index.html"


class LoginView(FormView):
    success_url = '/'
    form_class = FormCustomLogin
    # redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "core/login.html"

    def form_valid(self, form):
        data = form.cleaned_data

        user = authenticate(
            self.request,
            username=data['username'],
            password=data['password'])

        if user is not None:
            if user.is_active:
                login(self.request, user)
                return HttpResponseRedirect('/')
            else:
                msg = 'Conta inativa'
                messages.add_message(self.request, messages.WARNING, msg)
                return HttpResponseRedirect('/login/')
        else:
            msg = 'Usuário não encontrado'
            messages.add_message(self.request, messages.WARNING, msg)
            return HttpResponseRedirect('/login/')
        return super(LoginView, self).form_valid(form)


class FormCertificate(FormView):
    success_url = '/'
    form_class = FormCertificate
    # redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "core/sing_up.html"

    def form_valid(self, form):
        data = form.cleaned_data

        try:
            user = User.objects.get(email=data['email'])
        except Exception as e:
            user = None

        if user is None:
            msg = "Ops, tivemos um probleminha com seu cadastro," \
                "por favor faça um novo cadastro para receber seu certificado."
            messages.add_message(self.request, messages.WARNING, msg)
            return HttpResponseRedirect('/')
        else:
            context = {'user': user}
            # return render(self.request, 'core/certificate.html', context)
            return render_to_pdf('core/certificate.html', context)

        return super(FormCertificate, self).form_valid(form)


class LogoutView(CoreMixin, RedirectView):
    url = '/login/'
    permanent = True

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class SingUpView(FormView):
    success_url = '/'
    form_class = SignUpForm
    # redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "core/sing_up.html"

    def form_valid(self, form):

        data = form.cleaned_data
        user = User(**data)

        user.set_password(data['password'])

        user.save()

        msg = 'Conta inativa'
        messages.add_message(self.request, messages.WARNING, msg)
        return HttpResponseRedirect('/login/')

        return super(SingUpView, self).form_valid(form)


class UserCreateView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserForm3
    success_url = '/'
    success_message = "Cadastro realizado com sucesso."

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        data = form.cleaned_data
        user = User(**data)

        user.set_password("admin@12345")
        self.object = user
        return super().form_valid(form)

apps/core/templates/components/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >

  <!-- Optional theme -->
  {#<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">#}

  <title>{% block title %}Produtos - {% endblock title %}</title>
  {% block extra_css %}

  {% endblock %}
</head>

<body>
  {% include "components/navbar.html" %}

  <div class="container-fluid">
    {% include "components/messages.html" %}

    {% block body %}{% endblock %}
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery.mask.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript">

    function validarCPF(cpf) {
    cpf = cpf.replace(/[^\d]+/g,'');
    if(cpf == '') return false;
    // Elimina CPFs invalidos conhecidos
    if (cpf.length != 11 ||
        cpf == "00000000000" ||
        cpf == "11111111111" ||
        cpf == "22222222222" ||
        cpf == "33333333333" ||
        cpf == "44444444444" ||
        cpf == "55555555555" ||
        cpf == "66666666666" ||
        cpf == "77777777777" ||
        cpf == "88888888888" ||
        cpf == "99999999999")
            return false;
    // Valida 1o digito
    add = 0;
    for (i=0; i < 9; i ++)
        add += parseInt(cpf.charAt(i)) * (10 - i);
        rev = 11 - (add % 11);
        if (rev == 10 || rev == 11)
            rev = 0;
        if (rev != parseInt(cpf.charAt(9)))
            return false;
    // Valida 2o digito
    add = 0;
    for (i = 0; i < 10; i ++)
        add += parseInt(cpf.charAt(i)) * (11 - i);
    rev = 11 - (add % 11);
    if (rev == 10 || rev == 11)
        rev = 0;
    if (rev != parseInt(cpf.charAt(10)))
        return false;
    return true;
  }

    $('#id_phone').mask('(00) 0 0000-0000', {placeholder: "(__) _ ____-____"});
    $('#id_birth').mask("00/00/0000", {placeholder: "__/__/____"});
    $('#id_cpf').mask('000.000.000-00', {reverse: true});


    $('#id_cpf').change(function(e){
      cpf = $(this).val();

      if (!(validarCPF(cpf.replace(/[^0-9]/g, '')))) {
        alert("CPF inválido!");
        $('#id_cpf').val('');
      }

    });

    </script>
  {% block extra_js %}

  {% endblock %}
</body>

</html>

apps/core/templates/components/messages.html
{% load form_tags %}
<div class="row">
  <div class="col-lg-12">

    {% if messages %}
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} fade show" role="alert">
          <h5>Mensagem</h5>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
      <script>setTimeout(function(){$(".alert").remove();}, 5000);</script>
    {% endif %}

    {% if form and form.errors %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h5>Alerta</h5>
        <ul>
          {% for key, value in form.errors.items %}
          <li>{% get_label key form %} : {{ value|escape }}</li>
          {% endfor %}
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endif %}
  </div>
</div>

apps/core/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'core:index' %}">Inicio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">

      {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="EventMenu" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Eventos
          </a>
          <div class="dropdown-menu" aria-labelledby="EventMenu">
            <a class="dropdown-item" href="{% url 'event:list' %}">Listar</a>
            <a class="dropdown-item" href="{% url 'event:add' %}">Adicionar</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="PeopleMenu" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Usuários
          </a>
          <div class="dropdown-menu" aria-labelledby="PeopleMenu">
            <a class="dropdown-item" href="{% url 'people:list' %}">Listar</a>
            <a class="dropdown-item" href="{% url 'people:add' %}">Adicionar</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Sair</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:login' %}">Entrar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:sing_up' %}">Cadastrar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:certificate' %}">Certificado</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>