apps/event/urls.py
from django.urls import path, include
from apps.event import views

app_name = 'event'

urlpatterns = [
    path('', views.EventListView.as_view(), name='list'),
    path('add/', views.EventCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.EventUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.EventDeleteView.as_view(), name='delete'),
    path('code/<int:pk>/generate/', views.CodeFormView.as_view(), name='code'),
    path('<int:event_id>/action/', include('apps.action.urls')),
    path('<int:event_id>/product/', include('apps.product.urls')),
    path('<int:event_id>/participant/', include('apps.participant.urls')),
]

apps/participant/urls.py
from django.urls import path, include
from apps.participant import views

app_name = 'participant'

urlpatterns = [
    path('', views.ParticipantListView.as_view(), name='list'),
    path('add/', views.ParticipantCreateView.as_view(), name='add'),
    path(
        'detail/<int:pk>/',
        views.ParticipantDetailView.as_view(), name='detail'),
    path(
        'edit/<int:pk>/',
        views.ParticipantUpdateView.as_view(), name='edit'),
    path(
        'delete/<int:pk>/',
        views.ParticipantDeleteView.as_view(), name='delete'),
    path('balance/', include('apps.balance.urls')),
]

checkin_web/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings

urlpatterns = [
    path('', include('apps.core.urls')),
    path('event/', include('apps.event.urls')),
    path('user/', include('apps.people.urls')),
    # path('api/', include('apps.api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('api/', include('apps.api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/event/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.models import Sum
from django.urls import reverse


class Event(models.Model):
    PERIOD_CHOICE = (
        ('', '---------'),
        ('M', 'Matutino'),
        ('V', 'Vespetino'),
        ('N', 'Noturno'),
        ('I', 'Integral'),
    )
    name = models.CharField(
        _('Nome'), max_length=255, blank=False)
    date = models.DateField(_("Date"), blank=True, null=True)
    secret_key = models.CharField(
        _('Palavra chave'), max_length=255, blank=False)
    banner = models.ImageField(
        _('Banner'), upload_to='uploads/banner/', null=True, blank=True)
    text = models.TextField("Texto", null=True, blank=True)
    period = models.CharField(
        _('Periodo'), max_length=2, choices=PERIOD_CHOICE)
    created = models.DateTimeField(_('Criado'), auto_now_add=True)
    changed = models.DateTimeField(_('Alterado'), auto_now=True)
    start_code = models.IntegerField(_('Inicio códigos'), default=0)
    end_code = models.IntegerField(_('Fim códigos'), default=0)
    codes = models.FileField(blank=True, upload_to='uploads/codes/')

    participants = models.ManyToManyField(
        'people.User',
        through='event.Participant',
        through_fields=('event', 'user'),
    )

    @property
    def get_total_codes(self):
        return self.end_code - self.start_code

    def get_absolute_url(self):
        # return reverse('people.views.details', args=[str(self.id)])
        return reverse('event:detail', kwargs={'pk': self.id})

    def get_codes(self):
        pass

    def __str__(self):
        """Representation to str."""
        return '<Event %s>' % self.name

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"
        get_latest_by = 'created'
        ordering = ('-created',)


class Participant(models.Model):
    user = models.ForeignKey(
        'people.User', blank=True, null=True, verbose_name=_("Usuário"),
        on_delete=models.DO_NOTHING, related_name='participant_user')
    event = models.ForeignKey(
        'event.Event', blank=True, null=True, verbose_name=_("Evento"),
        on_delete=models.DO_NOTHING, related_name='participant_event')
    status = models.BooleanField("Status", default=True)
    created_at = models.DateTimeField("Created at", auto_now_add=True)
    updated_at = models.DateTimeField("Updated at", auto_now=True)
    code = models.CharField(
        _('Codigo'), max_length=255, blank=True)

    def get_credit(self):
        credit = self.movement_participant.filter(kind='C')\
            .aggregate(Sum('value'))
        debit = self.movement_participant.filter(kind='D')\
            .aggregate(Sum('value'))
        print(credit, debit)
        if credit['value__sum'] is None:
            credit['value__sum'] = 0

        if debit['value__sum'] is None:
            debit['value__sum'] = 0

        return credit['value__sum'] - debit['value__sum']

    def get_absolute_url(self):
        return reverse(
            'event:participant:detail',
            kwargs={'event_id': self.id, 'pk': self.id})

    class Meta:
        verbose_name = "Participante"
        verbose_name_plural = "Participantes"
        get_latest_by = 'created_at'
        ordering = ('-created_at',)

apps/event/forms.py
from django import forms
from django.conf import settings
from apps.event.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'date', 'secret_key', 'banner', 'text', 'period']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'secret_key': forms.TextInput(attrs={'class': 'form-control'}),
            'date': forms.DateInput(
                        format="%d/%m/%Y",
                        attrs={'class': 'form-control'}),
            'banner': forms.ClearableFileInput(
                        attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'period': forms.Select(attrs={'class': 'form-control'}),
        }
        fieldsets = (
            ('', {'fields': ('name',)}),
            ('', {'fields': ('date',)}),
            ('', {'fields': ('secret_key',)}),
            ('', {'fields': ('banner',)}),
            ('', {'fields': ('period',)}),
            ('', {'fields': ('text',)}),
        )


class CodeForm(forms.Form):
    start = forms.CharField(
        label='Início', required=True, initial="0",
        widget=forms.NumberInput(attrs={'class': 'form-control'}))
    end = forms.CharField(
        label='Fim', required=True, initial="0",
        widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        fieldsets = (
            ('', {'fields': ('start',)}),
            ('', {'fields': ('end',)}),
        )

apps/participant/forms.py
from django import forms
from django.conf import settings
from apps.people.models import User
from apps.event.models import Participant, Event


class ParticipantForm(forms.ModelForm):
    # event = forms.CharField(label='', widget=forms.HiddenInput)
    user = forms.ModelChoiceField(
        label='', queryset=User.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}))
    event = forms.ModelChoiceField(
        label='', queryset=Event.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Participant
        fields = ['user', 'event', 'status']
        fieldsets = (
            ('', {'fields': ('event',)}),
            ('', {'fields': ('user',)}),
            ('', {'fields': ('status',)}),
        )

apps/event/views.py
# Create your views here.
from django.views.generic import ListView, CreateView, \
    DetailView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from apps.event.models import Event
from apps.event.forms import EventForm, CodeForm
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib import messages
from django.template.defaultfilters import slugify
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from Crypto.Cipher import XOR
import base64
import os


def encrypt(key, plaintext):
    cipher = XOR.new(key)
    return base64.b64encode(cipher.encrypt(plaintext))


def decrypt(key, ciphertext):
    cipher = XOR.new(key)
    return cipher.decrypt(base64.b64decode(ciphertext))


class EventMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(EventMixin, self)\
            .dispatch(request, *args, **kwargs)


class EventListView(EventMixin, ListView):
    model = Event


class EventCreateView(EventMixin, CreateView):
    model = Event
    form_class = EventForm


class EventDetailView(EventMixin, DetailView):
    model = Event


class EventUpdateView(EventMixin, UpdateView):
    model = Event
    form_class = EventForm


class EventDeleteView(EventMixin, DeleteView):
    model = Event
    success_url = '/event/'


class CodeFormView(EventMixin, FormView):
    template_name = "event/event_form.html"
    form_class = CodeForm
    success_url = '/event/'

    def form_valid(self, form):
        data = form.cleaned_data
        event = get_object_or_404(Event, id=self.kwargs.get('pk'))
        path = os.path.join(settings.MEDIA_ROOT, "uploads", "codes")
        if not os.path.exists(path):
            os.makedirs(path)

        name = slugify("%d %s" % (event.id, event.name))
        filename = os.path.join(path, "%s.txt" % name)

        print(filename)

        the_file = open(filename, 'w')
        the_file.write('')
        the_file.close()

        for i in range(int(data['start']), int(data['end']) + 1):
            with open(filename, 'a') as the_file:
                code = encrypt(event.secret_key, "%d:%d" % (event.id, i))
                the_file.write('\"%s\"\n' % code.decode("utf-8"))
                the_file.close()

        p = filename.replace(settings.MEDIA_ROOT, '')

        print(p[1:len(p)])

        event.start_code = int(data['start'])
        event.end_code = int(data['end'])
        event.codes = p[1:len(p)]
        event.save()

        msg = "Códigos gerados com sucesso."
        messages.add_message(self.request, messages.SUCCESS, msg)
        return super(CodeFormView, self).form_valid(form)

apps/participant/views.py
# Create your views here.
from django.views.generic import ListView, CreateView, \
    DetailView, UpdateView, DeleteView
from apps.event.models import Participant
from apps.event.models import Event
from apps.participant.forms import ParticipantForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404


class ParticipantMixin(object):
    # @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ParticipantMixin, self)\
            .dispatch(request, *args, **kwargs)

    def get_initial(self):
        self.initial = {'event': self.kwargs.get('event_id')}
        return self.initial.copy()

    def get_context_data(self, **kwargs):
        context = super(ParticipantMixin, self).get_context_data(**kwargs)

        event = get_object_or_404(Event, id=self.kwargs.get('event_id'))

        context.update(dict(event=event))
        return context


class ParticipantListView(ParticipantMixin, ListView):
    model = Participant


class ParticipantCreateView(ParticipantMixin, CreateView):
    model = Participant
    form_class = ParticipantForm


class ParticipantDetailView(DetailView):
    model = Participant


class ParticipantUpdateView(UpdateView):
    model = Participant
    form_class = ParticipantForm


class ParticipantDeleteView(DeleteView):
    model = Participant
    success_url = '/'

apps/event/templates/event/event_detail.html
{% extends 'components/base.html' %}

{% block title %}
  {{ block.super }}
  Editar
{% endblock %}


{% block body %}

  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <!-- FORM -->
      <dl class="row">
        <dt class="col-sm-3">Nome</dt>
        <dd class="col-sm-9">{{object.name}}</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Data</dt>
        <dd class="col-sm-9">{{object.date}}</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Pulseiras</dt>
        <dd class="col-sm-9">{{object.get_total_codes}} - <a href="{{object.codes.url}}">baixar</a></dd>
      </dl>

    </div>
    <div class="col-md-6">
      <table class='table'>
        <thead>
          <tr>
            <th>Usuário</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for p in object.participant_event.all %}
            <tr>
              <td>{{p.user.first_name}}</td>
              <td>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <a href="{% url 'event:code' event.id %}" class="btn btn-primary">Gerar códigos</a>
    </div>
  </div>

{% endblock %}

apps/event/templates/event/event_form.html
{% extends 'components/base.html' %}

{% block title %}
  {{ block.super }}
  Editar
{% endblock %}


{% block body %}

  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <!-- FORM -->
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fieldset in form.fieldsets %}
        <br>
        <fieldset>
          <legend>{{ fieldset.title }}</legend>
          <div class="row">
          {% for field in fieldset %}

            <div class="col-md-6">
            <div class="control-group">
              <label class="control-label">{{ field.label }}</label>
              <div class="controls">
                {{ field }}
                {% if field.help_text  %}
                  <span class="help-inline">
                    {% for error in field.errors %}{{ error }}{% endfor %}
                  </span>
                {% endif %}
              </div>
            </div>
        </div>
          {% endfor %}
          </div>
        </fieldset>
        {% endfor %}
        <div class="form-actions">
          <a href="{% url 'event:list' %}" class="btn btn-danger">Cancelar</a>
          <button type="submit" class="btn btn-success">Salvar</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

apps/event/templates/event/event_list.html
{% extends 'components/base.html' %}


{% block title %} {{ block.super }} Todos {% endblock title %}


{% block body %}
  <div class="row">
    <div class="col-md-12">
      <h2>Eventos</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class='table'>
          <thead>
            <tr>
              <th>Nome</th>
              <th>Data</th>
              <th>Período</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for event in object_list %}
              <tr>
                <td>{{event.name}}</td>
                <td>{{event.date}}</td>
                <td>{{event.period}}</td>
                <td>
                  <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'event:detail' event.id %}" class="btn btn-primary">Ver</a>
                    <a href="{% url 'event:action:list' event.id %}" class="btn btn-primary">Ações</a>
                    <a href="{% url 'event:product:list' event.id %}" class="btn btn-primary">Produtos</a>
                    <a href="{% url 'event:participant:list' event.id %}" class="btn btn-primary">Participantes</a>
                    <a href="{% url 'event:edit' event.id %}" class="btn btn-secondary">Editar</a>
                    <a href="{% url 'event:delete' event.id %}" class="btn btn-danger">Deletar</a>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>


{% endblock %}

apps/event/templates/event/participant_detail.html
{% extends 'components/base.html' %}

{% block title %}
  {{ block.super }}
  Editar
{% endblock %}


{% block body %}

  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <!-- FORM -->
      <dl class="row">
        <dt class="col-sm-3">Nome</dt>
        <dd class="col-sm-9">{{object.user.get_full_name}}</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Data</dt>
        <dd class="col-sm-9">{{object.created}}</dd>
      </dl>
    </div>
    <div class="col-md-6">
      <table class='table'>
        <thead>
          <tr>
            <th>Usuário</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for p in object.participant_event.all %}
            <tr>
              <td>{{p.user.first_name}}</td>
              <td>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
    </div>
  </div>

{% endblock %}

apps/event/templates/event/participant_form.html
{% extends 'components/base.html' %}

{% block title %}
  {{ block.super }}
  Editar
{% endblock %}


{% block body %}

  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <!-- FORM -->
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fieldset in form.fieldsets %}
        <br>
        <fieldset>
          <legend>{{ fieldset.title }}</legend>
          <div class="row">
          {% for field in fieldset %}

            <div class="col-md-6">
            <div class="control-group">
              <label class="control-label">{{ field.label }}</label>
              <div class="controls">
                {{ field }}
                {% if field.help_text  %}
                  <span class="help-inline">
                    {% for error in field.errors %}{{ error }}{% endfor %}
                  </span>
                {% endif %}
              </div>
            </div>
        </div>
          {% endfor %}
          </div>
        </fieldset>
        {% endfor %}
        <div class="form-actions">
          <a href="{% url 'event:participant:list' event.id %}" class="btn btn-danger">Cancelar</a>
          <button type="submit" class="btn btn-success">Salvar</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

apps/event/templates/event/participant_list.html
{% extends 'components/base.html' %}

{% load balance_tags %}

{% block title %} {{ block.super }} Todos {% endblock title %}


{% block body %}
  <div class="row">
    <div class="col-md-12">
      <h2>Participantes</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <a href="{% url 'event:participant:add' event.id %}" class="btn btn-primary">Novo</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class='table'>
          <thead>
            <tr>
              <th>Usuário</th>
              <th>saldo</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for participant in object_list %}
              <tr>
                <td>{{participant.user.get_full_name}}</td>
                <td>{{participant.get_credit}}</td>
                <td>
                  <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'event:participant:detail' event.id participant.id %}" class="btn btn-primary">Ver</a>
                    <a href="{% url 'event:participant:balance:addcredit' event.id participant.id  'C' %}" class="btn btn-primary">Adicionar créditos</a>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>


{% endblock %}