apps/people/urls.py
from django.urls import path
from apps.people import views

app_name = 'people'

urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('add/', views.UserCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.UserUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete'),
    path('picture/', views.PictureCreateView.as_view(), name='picture'),
    path(
        'detail/<int:pk>/picture-delete/<int:picture_id>/',
        views.PictureDeleteView.as_view(),
        name='picture-delete'),
    path(
        'detail/<int:pk>/picture-detail/<int:picture_id>/',
        views.PictureDetailView.as_view(),
        name='picture-detail'),
    path(
        'picture-save/',
        views.PictureView.as_view(),
        name='picture-save'),
]

checkin_web/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings

urlpatterns = [
    path('', include('apps.core.urls')),
    path('event/', include('apps.event.urls')),
    path('user/', include('apps.people.urls')),
    # path('api/', include('apps.api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('api/', include('apps.api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/people/forms.py
from django import forms
from django.conf import settings
from apps.people.models import User, Picture
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.models import Group
import re
from django.core.exceptions import ValidationError


class UserForm2(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'email', 'first_name', 'last_name', 'phone', 'birth', 'rg',
            'cpf', 'gender', 'scholarity', 'city', 'province', 'street',
            'number', 'complement', 'neighborhood', 'postal_code']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control'}),
            'rg': forms.TextInput(attrs={'class': 'form-control'}),
            'birth': forms.DateInput(
                        format="%d/%m/%Y", attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),

            'scholarity': forms.Select(attrs={'class': 'form-control'}),

            'province': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'neighborhood': forms.TextInput(attrs={'class': 'form-control'}),
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'number': forms.TextInput(attrs={'class': 'form-control'}),
            'complement': forms.Textarea(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'})
        }
        fieldsets = (
            ('Dados Pessoais', {
                'fields': (
                    'first_name', 'last_name',
                    'gender', 'birth', 'rg', 'cpf',)
            }),
            ('Contato', {
                'fields': ('phone', 'email',)
            }),
            ('Localização', {
                'fields': (
                    'province', 'city', 'neighborhood', 'street',
                    'number', 'postal_code', 'complement')
            }),
        )


class UserForm3(forms.ModelForm):

    def clean_email(self):
        data = self.cleaned_data['email']

        try:
            user = User.objects.get(email=data)
        except Exception as e:
            print(e)
            user = None

        if not user:
            return data
        else:
            raise ValidationError("Email já cadastrado!")

    class Meta:
        model = User
        fields = [
            'email', 'first_name', 'last_name', 'phone', 'birth', 'gender']
        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'true'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'true'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'required': 'true'}),
            'phone': forms.TextInput(
                attrs={'class': 'form-control'}),
            'birth': forms.DateInput(
                        format="%d/%m/%Y", attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
        }
        fieldsets = (
            ('Dados Pessoais', {
                'fields': (
                    'first_name', 'last_name',
                    'gender', 'birth')
            }),
            ('Contato', {
                'fields': ('phone', 'email',)
            }),
        )



class UserForm(forms.Form):
    email = forms.EmailField(
        label='Email', max_length=80, required=True,
        widget=forms.EmailInput(
            attrs={
                'required': True,
                'autocomplete': 'off',
                'placeholder': 'Email'}))
    first_name = forms.CharField(
        label='Nome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Nome'}))
    last_name = forms.CharField(
        label='Sobrenome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Sobrenome'}))
    phone = forms.CharField(
        label='Telefone', max_length=80, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Telefone'}))

    brith = forms.DateField(
        label='Nascimento', required=True,
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(
            attrs={'required': True, 'placeholder': 'Nascimento'}))
    rg = forms.CharField(
        label='RG', required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'RG',
                'autocomplete': 'off',
                'required': True}))
    cpf = forms.CharField(
        label='CPF', required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'autocomplete': 'off',
                'placeholder': 'CPF'}))

    gender = forms.ChoiceField(
        label='Sexo', choices=User.GENDER_CHOICE, required=False,
        widget=forms.Select(attrs={'required': True, }))

    scholarity = forms.ChoiceField(
        label='Escolaridade', choices=User.SCHOLARITY_CHOICE, required=False,
        widget=forms.Select(attrs={'required': True, }))

    city = forms.CharField(
        label='Cidade', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Cidade'}))
    province = forms.ChoiceField(
        label='Estado', choices=User.PROVINCES_CHOICE,
        required=True,
        widget=forms.Select(attrs={}))
    street = forms.CharField(
        label='Rua', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Rua'}))
    number = forms.CharField(
        label='Número', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Número'}))
    complement = forms.CharField(
        label='Complemento', required=False,
        widget=forms.TextInput(
            attrs={'required': False, 'placeholder': 'Complemento'}))
    district = forms.CharField(
        label='Bairro', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Bairro'}))
    postal_code = forms.CharField(
        label='CEP', required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'CEP'}))

    def clean_phone(self):
        data = self.cleaned_data['phone']
        return re.sub('[^A-Za-z0-9]+', '', data)

    def clean_password_confirm(self):
        data = self.cleaned_data

        if data["password"] != data['password_confirm']:
            raise ValidationError("Senha não confere!")

        return data['password_confirm']

    def clean_cpf(self):
        data = self.cleaned_data['cpf']
        cpf = re.sub('[^A-Za-z0-9]+', '', data)

        try:
            user = User.objects.get(cpf=cpf)
        except Exception as e:
            user = None

        if not user:
            return cpf
        else:
            raise ValidationError("Cpf já cadastrado!")

    def clean_email(self):
        data = self.cleaned_data['email']

        try:
            user = User.objects.get(email=data)
        except Exception as e:
            user = None

        if not user:
            return data
        else:
            raise ValidationError("Email já cadastrado!")

    class Meta:
        fieldsets = (
            ('Dados Pessoais', {
                'fields': (
                    'first_name', 'last_name',
                    'gender', 'brith', 'rg', 'cpf',)
            }),
            ('Localização', {
                'fields': (
                    'province', 'city', 'street', 'number',
                    'complement', 'district', 'postal_code')
            }),
            ('Contato', {
                'fields': ('phone', 'email',)
            }),
            #     ('Dados Acesso', {
            #         'fields': ('password', 'password_confirm')
            #     }),
        )


class PictureForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        label='', queryset=User.objects.all(),
        widget=forms.HiddenInput)

    class Meta:
        model = Picture
        fields = ['photo', 'user']
        widgets = {
            'user': forms.HiddenInput,
            'photo': forms.FileInput(attrs={
                'required': True,
                'class': 'form-control'}),
        }


class PictureSaveForm(forms.Form):
    user = forms.ModelChoiceField(
        label='User', queryset=User.objects.all(),
        widget=forms.HiddenInput)
    image = forms.CharField(
        label='Image', required=False,
        widget=forms.Textarea(attrs={}))

    class Meta:
        model = Picture
        fields = ['photo', 'user']
        widgets = {
            'user': forms.HiddenInput,
            'photo': forms.FileInput(attrs={
                'required': True,
                'class': 'form-control'}),
        }


class FormProfile(forms.Form):
    first_name = forms.CharField(
        label='Nome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'class': 'form-control', 'placeholder': 'Nome'}))
    last_name = forms.CharField(
        label='Sobrenome', max_length=120, required=True,
        widget=forms.TextInput(
            attrs={'required': True, 'placeholder': 'Sobrenome'}))
    phone = forms.CharField(
        label='Telefone', max_length=80, required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'class': 'form-control',

apps/people/views.py
# Create your views here.
from django.views.generic import ListView, CreateView, \
    DetailView, UpdateView, DeleteView
from django.views.generic import View
from apps.people.models import User, Picture
from django.shortcuts import get_object_or_404
from apps.people.forms import UserForm2, PictureForm, PictureSaveForm
from django.urls import reverse
from django.conf import settings
from django.http import JsonResponse
from PIL import Image
import base64
import os
import uuid
import re
import io


class UserMixin(object):
    # @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UserMixin, self)\
            .dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserMixin, self).get_context_data(**kwargs)
        # context.update(dict(event=event))
        return context


class UserListView(ListView):
    model = User


class UserCreateView(CreateView):
    model = User
    form_class = UserForm2


class UserDetailView(DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        form = PictureForm(initial={'user': self.object.id})
        context.update(dict(form=form))
        return context


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm2


class UserDeleteView(DeleteView):
    model = User
    success_url = '/'


class PictureCreateView(CreateView):
    model = Picture
    form_class = PictureForm


class PictureDeleteView(DeleteView):
    model = Picture
    pk_url_kwarg = 'picture_id'

    def get_success_url(self):
        return reverse('people:detail', kwargs={'pk': self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        context = super(PictureDeleteView, self).get_context_data(**kwargs)
        user = get_object_or_404(User, id=self.kwargs.get('pk'))
        context.update(dict(user=user))
        return context


class PictureDetailView(DetailView):
    model = Picture
    pk_url_kwarg = 'picture_id'


class PictureView(View):

    def post(self, request, *args, **kwargs):
        response = {'saved': False}
        form = PictureSaveForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            image_data = re.sub('^data:image/.+;base64,', '', data['image'])
            im = Image.open(io.BytesIO(base64.b64decode(image_data)))

            temp_filename = '%s.png' % str(uuid.uuid1())
            temp_pach = os.path.join(settings.MEDIA_ROOT, "uploads/user")
            temp_pach_name = os.path.join(temp_pach, temp_filename)

            if not os.path.exists(temp_pach):
                os.makedirs(temp_pach)

            im.save(temp_pach_name)

            url = temp_pach_name.replace(settings.MEDIA_ROOT, '')

            pic = Picture()

            url = url[1:len(url)]

            pic.photo = url

            pic.user = data['user']

            pic.save()

            response = {'saved': True}

        return JsonResponse(response)

apps/people/templates/people/picture_confirm_delete.html
{% extends "components/base.html" %}

{% block body %}

  <div class="row">
    <div class="col-md-12">
      <h3>Você deseja deletar a imagem "{{ object }}" ?</h3>
      <form method="post" action="">
        {% csrf_token %}
        <br>
        <div class="row">
          <a class="btn btn-primary" href="{% url 'people:detail' user.id %}">
            Cancelar
          </a>
          <button class="btn btn-danger" type="submit" value="" class="btn green" >
            Deletar
          </button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

apps/people/templates/people/picture_detail.html
{% extends 'components/base.html' %}

{% block title %}
  {{ block.super }}
  Editar
{% endblock %}


{% block body %}

  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <!-- FORM -->
      <dl class="row">
        <dt class="col-sm-3">Nome</dt>
        <dd class="col-sm-9">{{object.photo.name}}</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Foto</dt>
        <dd class="col-sm-9">
          <img src="{{object.photo.url}}" alt="{{object.photo.name}}" class="img-thumbnail">
        </dd>
      </dl>
    </div>
  </div>
  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <a href="{% url 'people:detail' object.user.id %}" class="btn btn-primary">Voltar</a>
    </div>
  </div>

{% endblock %}

apps/people/templates/people/user_confirm_delete.html
{% extends "components/base.html" %}

{% block body %}

  <div class="row">
    <div class="col-md-12">
      <h3>Você deseja deletar o user "{{ object }}" ?</h3>
      <form method="post" action="">
        {% csrf_token %}
        <br>
        <div class="row">
          <a class="btn btn-primary" href="{% url 'people:detail' user.id %}">
            Cancelar
          </a>
          <button class="btn btn-danger" type="submit" value="" class="btn green" >
            Deletar
          </button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

apps/people/templates/people/user_detail.html
{% extends 'components/base.html' %}

{% load static %}

{% block title %}
  {{ block.super }}
  Editar
{% endblock %}


{% block body %}

  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <!-- FORM -->
      <dl class="row">
        <dt class="col-sm-3">Nome</dt>
        <dd class="col-sm-9">{{object.get_full_name}}</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Email</dt>
        <dd class="col-sm-9">{{object.email}}</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">CPF</dt>
        <dd class="col-sm-9">{{object.cpf}}</dd>
      </dl>
    </div>
    <div class="col-md-6">

      <form class="" action="{% url 'people:picture' %}" method="post" class="form-inline" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          {{form.user}}
          <div class="col-md-6">
            {{form.photo}}
          </div>
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary mb-2">Enviar</button>
            <button type="button" id="take" data-toggle="modal" data-target="#modal-foto" class="btn btn-primary mb-2">Tirar foto</button>
          </div>
        </div>
      </form>

      <table class='table'>
        <thead>
          <tr>
            <th>Foto</th>
            <th>Detectado</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for p in object.picture_user.all %}
            <tr>
              <td><img src="{{p.photo.url}}" width="70" /></td>
              <td>
                {% if p.face_found %}
                  <span class="badge badge-success">Success</span>
                {% else %}
                  <span class="badge badge-warning">Warning</span>
                {% endif %}
              </td>
              <td>
                <a class="btn btn-danger" href="{% url 'people:picture-delete' object.id p.id %}">
                  <span>Delete</span>
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
    </div>
  </div>

  <div class="modal" id="modal-foto" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Foto</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12">
              <video id="video" class="face-video" width="500" height="400" preload autoplay loop muted></video>
              <canvas id="canvas" class="face-canvas" width="500" height="400"></canvas>
              <img id='photo-img' src='' width="500" height="400"/>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" id="take-foto" class="btn btn-secondary">Tirar</button>
          <button type="button" id="send-foto" class="btn btn-secondary">Enviar</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>


{% endblock %}


{% block extra_js %}
  <script src="{% static 'js/tracking-min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/face-min.js' %}" type="text/javascript"></script>
  <script>
    var video = document.getElementById('video');
    var canvas = document.getElementById('canvas');
    var context = canvas.getContext('2d');
    var localMediaStream = null;

    function sendImage(img) {
      formData = new FormData();
      formData.append('image', img);
      formData.append('user', '{{object.id}}');
      formData.append('csrfmiddlewaretoken', "{{csrf_token}}");

      $.ajax({
        url: "{% url 'people:picture-save' %}",
        type: "POST",
        data: formData,
        processData: false,
        contentType: false,
        success: function (result) {
          console.log("Upload complete!");
          console.log(result);
          if (result.saved) {
            window.location.reload(true);
          }
        },
        error: function (error) {
          console.log("Something went wrong!");
        }
      });
    }

    $('#modal-foto').on('show.bs.modal', function (e) {
      $('#canvas').hide();
      $('#photo-img').hide();

      var snapshot = function() {
        if (localMediaStream) {
          // document.querySelector('a').href = i;
          $('#video').hide();
        	canvas.width = 500;
          canvas.height = 400;
          canvas.getContext('2d').drawImage(video, 0, 0, 500, 400);
          i = canvas.toDataURL('image/png');
          $('#photo-img').show();
          $('#photo-img').attr('src', i);
        }
      }

      video.addEventListener('click', snapshot, false);

      navigator.getUserMedia({video: true}, function(stream) {
        video.src = window.URL.createObjectURL(stream);
        localMediaStream = stream;
      }, function(error){console.error(error)});
    });

    $('#modal-foto').on('hide.bs.modal', function (event) {
      track = localMediaStream.getTracks()[0];
      track.stop();
    });

    $("#send-foto").click(function() {
      sendImage($('#photo-img').attr('src'));
    });

    $("#take-foto").click(function() {
      if (localMediaStream) {
        // document.querySelector('a').href = i;
        $('#video').hide();
      	canvas.width = 500;
        canvas.height = 400;
        canvas.getContext('2d').drawImage(video, 0, 0, 500, 400);
        i = canvas.toDataURL('image/png');
        $('#photo-img').show();
        $('#photo-img').attr('src', i);
      }
    });

  </script>

{% endblock %}

apps/people/templates/people/user_form.html
{% extends 'components/base.html' %}

{% block title %}
  {{ block.super }}
  Editar
{% endblock %}


{% block body %}

  <div class="row">
    <!-- COL -->
    <div class="col-md-6">
      <!-- FORM -->
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fieldset in form.fieldsets %}
        <br>
        <fieldset>
          <legend>{{ fieldset.title }}</legend>
          <div class="row">
          {% for field in fieldset %}

            <div class="col-md-6">
            <div class="control-group">
              <label class="control-label">{{ field.label }}</label>
              <div class="controls">
                {{ field }}
                {% if field.help_text  %}
                  <span class="help-inline">
                    {% for error in field.errors %}{{ error }}{% endfor %}
                  </span>
                {% endif %}
              </div>
            </div>
        </div>
          {% endfor %}
          </div>
        </fieldset>
        {% endfor %}
        <br />
        <div class="form-actions">
          <button type="submit" class="btn btn-success">Salvar</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

apps/people/templates/people/user_list.html
{% extends 'components/base.html' %}


{% block title %} {{ block.super }} Todos {% endblock title %}


{% block body %}
  <div class="row">
    <div class="col-md-12">
      <h2>Usuários</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <a href="{% url 'people:add' %}" class="btn btn-primary" > Novo </a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class='table'>
          <thead>
            <tr>
              <th>Nome</th>
              <th>Email</th>
              <th>CPF</th>
              <th>Saldo</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for user in object_list %}
              <tr>
                <td>{{user.get_full_name}}</td>
                <td>{{user.email}}</td>
                <td>{{user.cpf}}</td>
                <td>{{user.balance}}</td>
                <td>
                  <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'people:detail' user.id %}" class="btn btn-primary">Ver</a>
                    <a href="{% url 'people:edit' user.id %}" class="btn btn-secondary">Editar</a>
                    <a href="{% url 'people:delete' user.id %}" class="btn btn-danger">Deletar</a>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>


{% endblock %}